### ISSUE TITLE
Todo: more tests

### ISSUE THREAD

**Issue by cognitom** [cognitom/momy#7]
- [x] insert a single document
- [x] update a single document
- [x] convert values to SQL for each field type
- [x] insert multiple documents
- [x] insert/update many many documents
- [x] `fieldCase`
- [x] document deleting
- [ ] ~~CLI testing via `spawn`~~ maybe later
- [x] importing bulk docs
- [x] `prefix`
